progress on deleting an individual tag. tests.

diff --git a/delete_docker_registry_image b/delete_docker_registry_image
--- a/delete_docker_registry_image
+++ b/delete_docker_registry_image
@@ -5,9 +5,9 @@
 # and then run the command with an image name like this:
 # delete_docker_registry_image --image testrepo/awesomeimage --dry-run
 
-OPTS=`getopt -o vhnfi: --long verbose,help,dry-run,force,image: -n 'parse-options' -- "$@"`
+OPTS=`getopt -o vhnfpi: --long verbose,help,dry-run,force,prune,image: -n 'parse-options' -- "$@"`
 
-USAGE="Usage: delete_docker_registry_image --image testrepo/awesomeimage --dry-run --verbose"
+USAGE="Usage: delete_docker_registry_image --image testrepo/awesomeimage --dry-run --verbose ***OR*** delete_docker_registry_image --image testrepo/awesomeimage:killertag"
 
 if [ $? != 0 ] ; then echo "Failed parsing options. $USAGE" >&2 ; exit 1 ; fi
 
@@ -17,6 +17,7 @@ VERBOSE=false
 HELP=false
 FORCE=false
 DRY_RUN=false
+PRUNE=false
 
 while true; do
   case "$1" in
@@ -24,82 +25,48 @@ while true; do
     -h | --help )    HELP=true; shift ;;
     -n | --dry-run ) DRY_RUN=true; shift ;;
     -f | --force ) FORCE=true; shift ;;
+    -p | --prune ) PRUNE=true; shift ;;
     -i | --image ) IMAGE="$2"; shift; shift ;;
     -- ) shift; break ;;
     * ) break ;;
   esac
 done
 
-if [[ $HELP == true ]]
-then
+if $HELP; then
   echo $USAGE
   exit
 fi
 
-if [[ -z $REGISTRY_DATA_DIR ]]
-then
+if [[ -z $REGISTRY_DATA_DIR ]]; then
   REGISTRY_DATA_DIR=/opt/registry_data/docker/registry/v2
 fi
 
-cd $REGISTRY_DATA_DIR
-
-repositories_dir="repositories"
-if [[ ! -d "${repositories_dir}" ]] ; then
-  SCRIPTDIR=$( cd $(dirname $0) ; pwd -P )
-  echo "No repositories directory found inside REGISTRY_DATA_DIR '$REGISTRY_DATA_DIR'. Set REGISTRY_DATA_DIR correctly in this script ($SCRIPTDIR/$0) or pass it in as an environment variable."
-  exit 1
-fi
-repository_dir_for_image="${repositories_dir}/${IMAGE}"
-if [[ ! -d "${repository_dir_for_image}" ]] ; then
-  echo "No image '$IMAGE' found in repositories directory '$repositories_dir'"
-  exit 1
-fi
-
-blobs_to_delete=()
-link_files=$(find ${repository_dir_for_image} -name link)
-at_least_one_blob_was_used_elsewhere=false
-for file in $link_files
-do
-  sha256=$(cat $file | sed -e 's/sha256://g')
-
-  # i'm not sure if this egrep with the ./ prefix is super-portable, but it works for me
-  # and i want to be careful not to ignore another repo that might be using this blob
-  if find ./${repositories_dir} -name link | grep $sha256/link | egrep -v "^./${repository_dir_for_image}" > /dev/null
-  then
-    at_least_one_blob_was_used_elsewhere=true
-    if $VERBOSE
-    then
-      echo "found elsewhere: $sha256"
-      echo "Blob found in another repository. not deleting: $sha256"
-    fi
-  else
-    directory_prefix=${sha256:0:2}
-    blobs_to_delete+=("blobs/sha256/${directory_prefix}/${sha256}")
-    if $VERBOSE
-    then
-      echo "Blob not found in another repository. Marking for deletion: $sha256"
-    fi
-  fi
-done
-
-if [[ $at_least_one_blob_was_used_elsewhere == true || $FORCE == true ]]
-then
-  if $DRY_RUN
-  then
-    echo "DRY_RUN: would have deleted repository directory: $repository_dir_for_image"
-  else
-    rm -rf $repository_dir_for_image
-  fi
+function delete_blobs() {
   for blob_to_delete in "${blobs_to_delete[@]}"
   do
-    if $DRY_RUN
-    then
-      echo "DRY_RUN: would have deleted directory: $blob_to_delete"
+    directory_prefix_of_blob_to_delete=${blob_to_delete:0:2}
+    full_path_of_blob_to_delete="blobs/sha256/${directory_prefix_of_blob_to_delete}/${blob_to_delete}"
+    if $DRY_RUN; then
+      echo "DRY_RUN: would have deleted directory: $full_path_of_blob_to_delete"
     else
-      rm -rf $blob_to_delete
+      rm -rf $full_path_of_blob_to_delete
+      echo "DELETING: $layers_dir/$blob_to_delete"
+      echo "DELETING: $layers_dir/$blob_to_delete"
+      echo "DELETING: $layers_dir/$blob_to_delete"
+      rm -rf $layers_dir/$blob_to_delete
     fi
   done
-else
+  if $PRUNE; then
+    if $DRY_RUN; then
+      echo "DRY_RUN: not pruning empty blob dirs"
+    else
+      echo Pruning empty directories under $REGISTRY_DATA_DIR
+      find $REGISTRY_DATA_DIR/* -type d -empty -delete
+    fi
+  fi
+}
+
+function um_you_might_want_to_confirm_this() {
   echo "This is maybe fine but a bit worrisome."
   echo "None of the blobs that make up the image you want to delete were used by another image."
   echo
@@ -109,4 +76,189 @@ else
   echo "Because of this, we're aborting the delete."
   echo "If you're sure you actually want to delete this data, add a --force option"
   exit 1
+}
+
+cd $REGISTRY_DATA_DIR
+
+repositories_dir="repositories"
+if [[ ! -d "${repositories_dir}" ]] ; then
+  SCRIPTDIR=$( cd $(dirname $0) ; pwd -P )
+  echo "No repositories directory found inside REGISTRY_DATA_DIR '$REGISTRY_DATA_DIR'. Set REGISTRY_DATA_DIR correctly in this script ($SCRIPTDIR/$0) or pass it in as an environment variable."
+  exit 1
+fi
+
+TAG_SPLIT_ON_COLON=(${IMAGE//:/ })
+REPO=${TAG_SPLIT_ON_COLON[0]}
+TAG_IDENTIFIER=${TAG_SPLIT_ON_COLON[1]}
+
+if $VERBOSE; then
+  echo "Image to delete: $IMAGE"
+  echo "Repo: $REPO"
+  echo "Tag: $TAG_IDENTIFIER"
+fi
+
+repo_dir="${repositories_dir}/${REPO}"
+layers_dir="${repo_dir}/_layers/sha256"
+
+# code for deleting an entire repo
+if [[ -z $TAG_IDENTIFIER ]]; then
+  if $VERBOSE; then
+    echo "Deleting repo: $IMAGE"
+  fi
+  repository_dir_for_image="${repositories_dir}/${IMAGE}"
+  if [[ ! -d "${repo_dir}" ]] ; then
+    echo "No repository '$REPO' found in repositories directory '$repositories_dir'"
+    exit 1
+  fi
+
+  blobs_to_delete=()
+  link_files=$(find ${repo_dir} -name link)
+  at_least_one_blob_was_used_elsewhere=false
+  for file in $link_files
+  do
+    sha256=$(cat $file | sed -e 's/sha256://g')
+
+    # i'm not sure if this egrep with the ./ prefix is super-portable, but it works for me
+    # and i want to be careful not to ignore another repo that might be using this blob
+    if find ./${repositories_dir} -name link | grep $sha256/link | egrep -v "^./${repo_dir}" > /dev/null
+    then
+      at_least_one_blob_was_used_elsewhere=true
+      if $VERBOSE; then
+        echo "Blob found in another repository. not deleting: $sha256"
+      fi
+    else
+      blobs_to_delete+=("${sha256}")
+      if $VERBOSE; then
+        echo "Blob not found in another repository. Marking for deletion: $sha256"
+      fi
+    fi
+  done
+
+  if [[ $at_least_one_blob_was_used_elsewhere == true || $FORCE == true ]]; then
+    if $DRY_RUN; then
+      echo "DRY_RUN: would have deleted repository directory: $repo_dir"
+    else
+      rm -rf $repo_dir
+    fi
+    delete_blobs
+  else
+    um_you_might_want_to_confirm_this
+  fi
+  # end code for deleting an entire repo
+
+else
+  # user wanted to delete a specific tag, not an entire repo/image
+  dir_for_tags="${repo_dir}/_manifests/tags"
+  dir_for_tag="${dir_for_tags}/${TAG_IDENTIFIER}"
+
+  if [[ ! -d "${dir_for_tag}" ]]; then
+    echo "No tag found in '${dir_for_tag}'"
+    exit 1
+  fi
+
+  blobs_to_delete=()
+  link_files=$(find ${dir_for_tag}/index/sha256 -name link)
+
+  digests=()
+
+  for file in $link_files
+  do
+    digests+=($(cat $file | sed -e 's/sha256://g'))
+  done
+
+  unique_manifest_digests=$(echo "${digests[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
+  dir_for_revisions="${repositories_dir}/${REPO}/_manifests/revisions"
+  manifest_revisions_to_delete=()
+  # FIXME: delete revisions
+  # manifest_revision_dir="${dir_for_revisions}/sha256/${manifest_digest}"
+
+  if ! hash jq 2>/dev/null; then
+    echo "Sorry about this, but the jq program is required to delete tags. https://stedolan.github.io/jq/download/"
+    exit 1
+  fi
+
+  layer_digests_for_tag=()
+
+  for manifest_digest in ${unique_manifest_digests[@]}; do
+    if $VERBOSE; then
+      echo "looking at digest $manifest_digest"
+    fi
+    manifest_revisions_to_delete+=("$dir_for_revisions/sha256/$manifest_digest")
+    directory_prefix=${manifest_digest:0:2}
+
+    for filesystem_layer_sha256 in $(cat blobs/sha256/${directory_prefix}/${manifest_digest}/data  | jq -r '.fsLayers | map(.blobSum)[]' | sort | uniq); do
+      digest=$(echo $filesystem_layer_sha256 | sed -e 's/sha256://g')
+      layer_digests_for_tag+=("$digest")
+    done
+  done
+
+  unique_layer_digests_for_tag=$(echo "${layer_digests_for_tag[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' ')
+
+  for digest in ${unique_layer_digests_for_tag[@]}; do
+    # i'm not sure if this egrep with the ./ prefix is super-portable, but it works for me
+    # and i want to be careful not to ignore another repo that might be using this blob
+    if find ./${repositories_dir} -name link | grep $digest/link | egrep -v "^./${dir_for_tag}" | egrep -v "^./${layers_dir}" > /dev/null
+    then
+      at_least_one_blob_was_used_elsewhere=true
+      if $VERBOSE; then
+        echo "Blob found in another repository. not deleting: $digest"
+      fi
+    else
+      if $VERBOSE; then
+        echo "Blob not found in another repo. checking to make sure no other tags from the same repo are using it"
+      fi
+      digest_in_use_within_same_repo=false
+      for tag_subdir in $(ls $dir_for_tags | grep -v $TAG_IDENTIFIER); do
+        manifest_digest_for_tag=$(cat "${dir_for_tags}/${tag_subdir}/current/link" | sed -e 's/sha256://g')
+        directory_prefix_for_tag_digest=${manifest_digest_for_tag:0:2}
+        for filesystem_layer_sha256_for_tag in $(cat blobs/sha256/${directory_prefix_for_tag_digest}/${manifest_digest_for_tag}/data  | jq -r '.fsLayers | map(.blobSum)[]' | sort | uniq); do
+          used_digest=$(echo $filesystem_layer_sha256_for_tag | sed -e 's/sha256://g')
+          if [ "$used_digest" == "$digest" ]; then
+            digest_in_use_within_same_repo=true
+            another_tag_using=$tag_subdir
+          fi
+        done
+      done
+
+      if [[ $digest_in_use_within_same_repo == true ]]; then
+        if $VERBOSE; then
+          echo "Found another tag using digest: $digest. tag was: $another_tag_using"
+        fi
+      else
+        blobs_to_delete+=("${digest}")
+        if $VERBOSE; then
+          echo "Blob not found in another repository or sibling tag. Marking for deletion: $digest"
+        fi
+      fi
+    fi
+
+  done
+
+  if [[ $at_least_one_blob_was_used_elsewhere == true || $FORCE == true ]]; then
+    if $DRY_RUN; then
+      echo "DRY_RUN: would have deleted tag directory: $dir_for_tag"
+    else
+      rm -rf $dir_for_tag
+    fi
+
+    for manifest_revision_to_delete in "${manifest_revisions_to_delete[@]}"; do
+      link_files_for_manifest_revision=$(find ${manifest_revision_to_delete} -name link)
+
+      for file in $link_files_for_manifest_revision
+      do
+        digest_for_manifest_revision=($(cat $file | sed -e 's/sha256://g'))
+        blobs_to_delete+=("${digest_for_manifest_revision}")
+      done
+
+      if $DRY_RUN; then
+        echo "DRY_RUN: would have deleted manifest revision: $manifest_revision_to_delete"
+      else
+        rm -rf $manifest_revision_to_delete
+      fi
+    done
+
+    delete_blobs
+  else
+    um_you_might_want_to_confirm_this
+  fi
 fi
